MH - output changelog data as jsonl
aidantd/ECE595-RegexBugs pull request #8
Opened 2024-03-26 12:42 UTC by OdysseusMiX

Output training and test JSONL files for fine-tuning of OpenAI models.

2024-04-05 18:24 UTC, OdysseusMiX commented
This PR includes all scripts needed to process the PCRE2 changelog and create a CSV file of the changelog with labels for "Evolution?" (Y/N) provided by a fine-tuned ChatGPT 3.5 AI model. A markdown file annotating the processing steps has also been provided. Data output files are ignored by and are not included in the PR. The OpenAI API key is in a .env file locally that is ignored by Git to prevent uploading of API secrets.

2024-04-05 19:59 UTC, aidantd requested changes
It looks as though you forked the repo instead of creating a branch, because of this it does not seem to be diffing correctly. One example of this is that you wrote your code in aiCategorizer.py and that is where I had written the bert logic. This does not show up in the diff and we should have seperate files for the different ai categorizers

2024-04-06 18:05 UTC, OdysseusMiX commented
I think the issue was simply a merge conflict from your PR that wasn't in main when I last updated mine. I've fetched the latest changes from main and merged them in so that this should be a simple fast forward merge. I wasn't really using `aiCategorizer.py` since I had created `aiCategorizer_pcre2.py`. Should be good to go now.

2024-04-06 20:06 UTC, aidantd approved these changes

2024-04-10 23:07 UTC, merged